import type { Metadata } from "next";
import { Share_Tech, Barlow, Concert_One, Poppins } from "next/font/google";
import "./globals.css";
import ParticleComponent from "@/components/UI/ParticleWrapper";
import Navbar from "@/components/Menus/Navbar";

const shareTech = Share_Tech({
  variable: "--font-share-tech",
  subsets: ["latin"],
  display: "swap",
  weight: "400",
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  display: "swap",
  weight: "400",
});

const barlow = Barlow({
  variable: "--font-barlow",
  subsets: ["latin"],
  display: "swap",
  weight: "400",
});

const concertOne = Concert_One({
  variable: "--font-concert-one",
  subsets: ["latin"],
  display: "swap",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Ali Riz Abadian | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en">
        <body
          className={`${shareTech.variable} ${barlow.variable} ${concertOne.variable} ${poppins.variable} antialiased container  mx-auto`}
        >
          <Navbar />
          {children}
        </body>
      </html>
      <ParticleComponent />
    </>
  );
}
